# Generated by Django 5.0.6 on 2024-05-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('songid', models.IntegerField()),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(unique=True)),
                ('creat_la', models.DateField(auto_now_add=True)),
                ('refresh_token', models.CharField(max_length=150)),
                ('access_token', models.CharField(max_length=150)),
                ('expira_la', models.DateTimeField()),
                ('tip_token', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotifyid', models.CharField(max_length=64, unique=True)),
                ('genreid', models.IntegerField()),
                ('artists', models.CharField(max_length=200)),
                ('releasedate', models.DateField()),
                ('durationms', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('explicit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotifyid', models.CharField(max_length=32, unique=True)),
                ('favoriteGenreId', models.IntegerField()),
                ('averageDuration', models.IntegerField()),
                ('averageYear', models.IntegerField()),
                ('explicitRatio', models.FloatField()),
            ],
        ),
    ]
