# Generated by Django 5.0.6 on 2024-05-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_rating_token_track_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='userid',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
