# Generated by Django 5.0.6 on 2024-05-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_alter_token_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='averageDuration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='averageYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='explicitRatio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='favoriteGenreId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='spotifyid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
